# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f38996a63b81d0c46c4bd25f67f774665d150384a3ee607667bd61883509c10e50108abdf8304a4c745d6e3a9e4ab2ff5883add9d6ab80d16fc659b8ed44d095

test:
  secret_key_base: 41b509159e57a0053da4aeb57051a61e2961b3d421d849ed8fad1d6dc675bd3a436385a137936a9e3484fd9f2efb731eb68de7fc9db8d214b0898e2bebd7aff0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
